openapi: 3.0.1
info:
  title: Eng Microservice Registry API
  description: 'Eng Microservice Registry ##API##.'
  version: 1.0.0
servers:
- url: https://eng-registry:1112/
- url: http://eng-registry:1111/
paths:
  /service/{servicename}/info:
    get:
      summary: legge le info di un servizio
      parameters:
      - name: servicename
        in: path
        description: service name
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInfo'
    post:
      summary: salva le info di un servizio
      parameters:
      - name: servicename
        in: path
        description: service name
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInfo'
      requestBody:
        $ref: '#/components/requestBodies/ServiceInfo'
  /service/{servicename}/config:
    get:
      summary: bla bla
      parameters:
      - name: servicename
        in: path
        description: service name
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInfo'
  /service/{servicename}/endpoint:
    put:
      summary: bla bla
      parameters:
      - name: servicename
        in: path
        description: service name
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        $ref: '#/components/requestBodies/ServiceEndpointInfo'

      responses:
        200:
          description: successful operation
components:
  schemas:
    ServiceInfo:
      type: object
    ServiceEndpointInfo:
      type: object
      properties:
        url:
          type: string
        expire: 
          type: number
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
  requestBodies:
    ServiceEndpointInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceEndpointInfo'
    ServiceInfo:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ServiceInfo'
